### ISSUE TITLE
How to integrate it in Android app

### ISSUE THREAD

**Issue by sureshsmartrxin** [priaid-eHealth/symptomchecker#1]
Hi There, 
We are trying to integrate this symptomchecker in Android apps,

If you can give me SDK or webview, please share here

Thankfully
suresh@smartrx.in

**Comment by sureshsmartrxin** [comment]
Hi thank you for your response but How could I do it in Native Android

**Comment by flxkalu** [comment]
Hi @sureshsmartrxin were you aboe to do it in native android. If you were pls share i’m having same issue now
