### ISSUE TITLE
After installation integrating symptom checker with chatterbot the program is showing the error

### ISSUE THREAD

**Issue by vaibsshukla** [priaid-eHealth/symptomchecker#6]
vaibhav@b3ds-HP-Z210-Workstation:~/symptomchecker/Python$ python PriaidDiagnosisClientDemo.py

Traceback (most recent call last):
  File "PriaidDiagnosisClientDemo.py", line 198, in <module>
    diagnosisClientDemo = PriaidDiagnosisClientDemo()
  File "PriaidDiagnosisClientDemo.py", line 18, in __init__
    self._diagnosisClient = PriaidDiagnosisClient.DiagnosisClient(username, password, authUrl, language, healthUrl)
  File "/home/vaibhav/symptomchecker/Python/PriaidDiagnosisClient.py", line 27, in __init__
    self._token = self._loadToken(username, password, authServiceUrl)
  File "/home/vaibhav/symptomchecker/Python/PriaidDiagnosisClient.py", line 31, in _loadToken
    rawHashString = hmac.new(bytes(password, encoding='utf-8'), url.encode('utf-8')).digest()
TypeError: str() takes at most 1 argument (2 given)

**Comment by vaibsshukla** [comment]
@fabiants  and @priaid  can you please help me with this. After creating the fresh environment problem is not resolved.

**Comment by fabiants** [comment]
Did you check the credentials and and endpoint? Please also ensure that you are using the right pair (production or sandbox) of endpoint and credentials.
If this is correct, did you adjust anything? Which version of Python do you use?

**Comment by vaibsshukla** [comment]
@fabiants  thanks the issue is resolved.

the another issue which i m facing is after calling the PriaidDiagnosisClientDemo() function  

 (newenv) vaibhav@b3ds-HP-Z210-Workstation:~/symptomchecker/Python$ python PriaidDiagnosisClientDemo.py

+++++++++++++++++++++++++++++++++++++++++++++
Response from method loadBodyLocations:
[{"ID": 16, "Name": "Abdomen, pelvis & buttocks"}, {"ID": 7, "Name": "Arms & shoulder"}, {"ID": 15, "Name": "Chest & back"}, {"ID": 6, "Name": "Head, throat & neck"}, {"ID": 10, "Name": "Legs"}, {"ID": 17, "Name": "Skin, joints & general"}]
+++++++++++++++++++++++++++++++++++++++++++++
---------------------------------------------
Body locations:
---------------------------------------------
Abdomen, pelvis & buttocks (16)
Arms & shoulder (7)
Chest & back (15)
Head, throat & neck (6)
Legs (10)
Skin, joints & general (17)
---------------------------------------------
Sublocations for randomly selected location Skin, joints & general
---------------------------------------------

+++++++++++++++++++++++++++++++++++++++++++++
Response from method loadBodySubLocations:
[{"ID": 47, "Name": "General, joints & other"}, {"ID": 46, "Name": "Skin"}]
+++++++++++++++++++++++++++++++++++++++++++++
General, joints & other (47)
Skin (46)
---------------------------------------------
Sublocations for randomly selected location General, joints & other
---------------------------------------------
Traceback (most recent call last):
  File "PriaidDiagnosisClientDemo.py", line 201, in <module>
    diagnosisClientDemo.simulate()
  File "PriaidDiagnosisClientDemo.py", line 31, in simulate
    selectedSymptoms = self._loadSublocationSymptoms(selectedSublocationID)
  File "PriaidDiagnosisClientDemo.py", line 94, in _loadSublocationSymptoms
    symptoms = self._diagnosisClient.loadSublocationSymptoms(subLocId, PriaidDiagnosisClient.SelectorStatus.Man)
AttributeError: 'Enum' object has no attribute 'Man'

**Comment by priaid** [comment]
This looks quite odd. The SelectorStatus Enum is defined in PriaidDiagnosisClient.py line 9 (according to our example). What is your Python version?

Once in a while, it can also happen that the demo ends up with not valid data as it's based on random inputs and a reduced data set (on the sandbox). In this case, just start again the demo and you should get other results.

P.S.: You can best contact us by e-mail: support@priaid.ch.
Kind greetings,
Your priaid team

**Comment by vikash130795** [comment]
> @fabiants thanks the issue is resolved.
> 
> the another issue which i m facing is after calling the PriaidDiagnosisClientDemo() function
> 
> (newenv) vaibhav@b3ds-HP-Z210-Workstation:~/symptomchecker/Python$ python PriaidDiagnosisClientDemo.py
> 
> ## +++++++++++++++++++++++++++++++++++++++++++++
> Response from method loadBodyLocations:
> [{"ID": 16, "Name": "Abdomen, pelvis & buttocks"}, {"ID": 7, "Name": "Arms & shoulder"}, {"ID": 15, "Name": "Chest & back"}, {"ID": 6, "Name": "Head, throat & neck"}, {"ID": 10, "Name": "Legs"}, {"ID": 17, "Name": "Skin, joints & general"}]
> +++++++++++++++++++++++++++++++++++++++++++++
> ## Body locations:
> ## Abdomen, pelvis & buttocks (16)
> Arms & shoulder (7)
> Chest & back (15)
> Head, throat & neck (6)
> Legs (10)
> Skin, joints & general (17)
> ## Sublocations for randomly selected location Skin, joints & general
> ## +++++++++++++++++++++++++++++++++++++++++++++
> Response from method loadBodySubLocations:
> [{"ID": 47, "Name": "General, joints & other"}, {"ID": 46, "Name": "Skin"}]
> +++++++++++++++++++++++++++++++++++++++++++++
> General, joints & other (47)
> Skin (46)
> ## Sublocations for randomly selected location General, joints & other
> Traceback (most recent call last):
> File "PriaidDiagnosisClientDemo.py", line 201, in
> diagnosisClientDemo.simulate()
> File "PriaidDiagnosisClientDemo.py", line 31, in simulate
> selectedSymptoms = self._loadSublocationSymptoms(selectedSublocationID)
> File "PriaidDiagnosisClientDemo.py", line 94, in _loadSublocationSymptoms
> symptoms = self._diagnosisClient.loadSublocationSymptoms(subLocId, PriaidDiagnosisClient.SelectorStatus.Man)
> AttributeError: 'Enum' object has no attribute 'Man'

Hello Vaibhav,

Can you please let me know. How you solved this issue:
Traceback (most recent call last):
File "PriaidDiagnosisClientDemo.py", line 198, in
diagnosisClientDemo = PriaidDiagnosisClientDemo()
File "PriaidDiagnosisClientDemo.py", line 18, in init
self._diagnosisClient = PriaidDiagnosisClient.DiagnosisClient(username, password, authUrl, language, healthUrl)
File "/home/vaibhav/symptomchecker/Python/PriaidDiagnosisClient.py", line 27, in init
self._token = self._loadToken(username, password, authServiceUrl)
File "/home/vaibhav/symptomchecker/Python/PriaidDiagnosisClient.py", line 31, in _loadToken
rawHashString = hmac.new(bytes(password, encoding='utf-8'), url.encode('utf-8')).digest()
TypeError: str() takes at most 1 argument (2 given)
