### ISSUE TITLE
How to use symptomcheckeravatar in Android app?

### ISSUE THREAD

**Issue by imran-samed** [priaid-eHealth/symptomchecker#8]
I'm using symptomchecker API in my Android Application.

now I also wanna use symptomcheckeravatar in Application as showing in below link.

https://apimedic.com/symptomcheckeravatar

Is there any way to use the same functionality in Android App?

Any kind of help will be appreciated.

**Comment by priaid** [comment]
Kindly contact our Support-Team at support@priaid.ch.
